controllers/SettingsController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use app\models\settings\Settings;

/**
 * Settings Controller
 */
class SettingsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'change-setting-value-ajax' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @throws NotFoundHttpException
     * @throws BadRequestHttpException
     * @return mixed
     */
    public function actionChangeSettingValueAjax()
    {
        if(isset($_POST['key']) == false || isset($_POST['value']) == false)
        {
            throw new BadRequestHttpException('Отсутствуют обязательные параметры: key, value');
        } else {
            $key = $_POST['key'];
            $value = $_POST['value'];
        }

        Yii::$app->response->format = Response::FORMAT_JSON;

        $setting = Settings::findByKey($key);

        if($setting == null)
        {
            throw new NotFoundHttpException('Настройка не найдена');
        }

        $setting->value = $value;
        $result = $setting->save(false);

        return ['result' => $result];
    }

    /**
     * Список параметров
     * @return mixed
     */
    public function actionIndex()
    {

        $request = Yii::$app->request;

        if($request->isPost)
        {
            $data = $request->post();
            foreach ($data['Settings'] as $key => $value){
                $setting = Settings::findByKey($key);

                if($setting != null){
                    $setting->value = $value;
                    $setting->save();
                    Yii::$app->session->setFlash('success', 'Настройки успешно сохранены');
                }
            }
        }

        $settings = Settings::find()->all();

        return $this->render('index', [
            'settings' => $settings,
        ]);
    }

}

controllers/TaskFullController.php
<?php

namespace app\controllers;

use app\models\AddFilesForm;
use app\models\attachment\AddAttachmentsForm;
use app\models\behaviors\UpdateOnlineBehavior;
use app\models\chat\SendMessageForm;
use app\models\forms\UploadForm;
use app\models\message\Message;
use app\models\message\MessageFile;
use app\models\notification\Notification;
use app\models\task\Task;
use app\models\task\TaskEvent;
use app\models\task\TaskStatus;
use app\models\team\TeamMember;
use app\Rf\Modules\Users\models\User;
use app\widgets\chat\Chat;
use app\widgets\task\full_task\FullTaskTeam;
use app\widgets\task\FullTaskInfo;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskFullController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'updateOnline' => UpdateOnlineBehavior::class,
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'new-messages' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @var Task $task
     */
    protected $task;

    protected function seenTask()
    {
        //delete notification for task for this user
        Notification::deleteAll([
            'task_id' => $this->task->id,
            'user_id' => User::current()->id,
        ]);

        //change status WAIT=>SEEN if user is executor
        if ($this->task->status === TaskStatus::wait() &&
            $this->task->isExecutor(User::current())
        ) {
            $this->task->status = TaskStatus::seen();
            $this->task->save();

            TaskEvent::changeStatus()->trigger($this->task, User::current());
        }
    }

    public function actionMessageDelete($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if(Yii::$app->user->identity->getIsAdmin() == false)
        {
            throw new ForbiddenHttpException('Доступ запрещен');
        }

        $message = Message::findOne($id);

        if($message != null){
            $message->delete();

            return ['result' => true];
        }

        return ['result' => false, 'error' => 'Message not found'];
    }

    public function actionChangeStatus()
    {
        if (!\Yii::$app->request->isPost) {
            return;
        }

        $taskId = \Yii::$app->request->post('taskId');
        $task = Task::findOne($taskId);

        $statusId = \Yii::$app->request->post('statusId');

        $newStatus = TaskStatus::getInstance($statusId);

        if ($task->status !== $newStatus) {
            $task->status = $newStatus;
            if ($task->save()) {
                TaskEvent::changeStatus()->trigger($task, User::current());
            }
        }

        return FullTaskInfo::widget(['task' => $task]);
    }


    public function actionAddObserver()
    {
        if (!\Yii::$app->request->isPost) {
            return;
        }

        $taskId = \Yii::$app->request->post('TeamMember')['task_id'];
        $task = Task::findOne($taskId);

        $observer = TeamMember::observer(null, $task);
        if ($observer->load(\Yii::$app->request->post())) {
            if ($observer->save()) {
                TaskEvent::observerAdd()->trigger($task, User::current(), [
                    'observer' => $observer,
                ]);
            }
        }
        return FullTaskTeam::widget(['task' => $task]);
    }

    public function actionAttachments($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = Task::findOne($id);
        if($model == null){
            throw new NotFoundHttpException();
        }

        return [
            'title' => 'Вложения запроса #',
            'content' => $this->renderAjax('attachments', ['model' => $model]),
            'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default btn-block', 'data-dismiss' => 'modal'])
        ];
    }


    /**
     * @return string|void
     * @throws \Exception
     */
    public function actionSendMessage()
    {
        if (!\Yii::$app->request->isPost) {
            return;
        }

        $sendMessageForm = new SendMessageForm();
        $sendMessageForm->load(\Yii::$app->request->post());

//        echo '123';

        $uploadModel = new UploadForm(['uploadPath' => 'uploads/chat/', 'file' => $_FILES['UploadForm']]);
        $uploadModel->file = UploadedFile::getInstances($uploadModel, 'file');

        $task = Task::findOne($sendMessageForm->taskId);
        if ($sendMessageForm->validate()) {
//            echo '456';
            $message = $sendMessageForm->message;
            $user = $message->user;
            if ($message->text != null || !empty($uploadModel->file)) {
//                echo '789';
                $message->save();

                // Сохраняем фалы если таковые были загружены
                if($uploadModel->upload()){
                    if($uploadModel->fullUploadedFilePath != null)
                    {
                        foreach ($uploadModel->fullUploadedFilePath as $file)
                        {
                            $messageFile = new MessageFile([
                                'message_id' => $message->id,
                                'name' => $file['name'],
                                'path' => $file['path']
                            ]);
                            $messageFile->save(false);
                        }
                    }
                }

                if ($task->getStatus() === TaskStatus::seen() &&
                    $task->isExecutor(User::current())
                ) {
                    //change status BACK if user is executor
                    $task->setStatus(TaskStatus::back());
                    $task->save();

                    TaskEvent::changeStatus()->trigger($task, User::current());
                } else if ($task->getStatus() === TaskStatus::back() &&
                    $task->isAuthor(User::current())
                ) {
                    //change status WAIT if user is Author
                    $task->setStatus(TaskStatus::wait());
                    $task->save();
                    TaskEvent::changeStatus()->trigger($task, User::current());
                }

                TaskEvent::chatMessage()->trigger($task, User::current());

                $chatMembers = array_values(ArrayHelper::map(TeamMember::find()->where(['task_id' => $task->id])->andWhere(['!=', 'user_id', $user->id])->all(), 'task_id', 'user_id'));
                $users = ArrayHelper::map(User::findAll($chatMembers), 'id', 'id');

                Yii::$app->pusher
                    ->addReceivers($users)
                    ->setAdditionalData(['task_id' => $task->id])
                    ->compose([
                        'title' => "Пожалуйста, доработайте запрос №{$task->id}",
                        'body' => 'Комментарий:  '.$sendMessageForm->text,
                        'icon' => '',
                        'url' => Url::toRoute(['index', 'taskId' => $task->id], 'https'),
                    ])->send();
            }
        }

        return Chat::widget(['task' => $task]);
    }

    public function actionTestPush()
    {
        $result = Yii::$app->pusher
            ->addReceivers(['9' => '9'])
            ->compose([
                'title' => "Заголовок",
                'body' => 'Тело',
                'icon' => '',
//                'click_action' => Url::toRoute(['index', 'id' => $task->id]),
            ])->send();


        var_dump($result);
    }


    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex($taskId)
    {

        /**
         * @var Task $task
         */
        $this->task = Task::find()
            ->where(['id' => $taskId])
            ->limit(1)
            ->one();
        //mark as seen task
        $this->seenTask();

        return $this->render('index', [
            'task' => $this->task,
            'filesForm' => new AddAttachmentsForm(['taskId' => $this->task->id]),
        ]);
    }

    public function actionNewMessages($taskId)
    {
        if (!\Yii::$app->request->isPost) {
            return;
        }

        $lastMessage = \Yii::$app->request->post('lastMessage');
        /**
         * @var Task $task
         */
        $this->task = Task::find()
            ->where(['id' => $taskId])
            ->limit(1)
            ->one();

        $new = $this->task->getMessages()
            ->andWhere(['>', 'created_at', $lastMessage]
            )->count();

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return ['new' => $new];
    }
}

views/task/_columns.php
<?php

use app\models\message\Message;
use kartik\daterange\DateRangePicker;
use yii\helpers\Html;
use yii\helpers\Url;

$setting = \app\models\settings\Settings::findByKey('table_row_line_height');

$lineHeight = $setting->value * 10;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
        'hiddenFromExport' => true,
    ],
//    [
//        'class' => 'kartik\grid\SerialColumn',
//        'width' => '30px',
//    ],
    [
        'class' => '\app\widgets\columns\DataColumn',
        'attribute' => 'id',
        'contentOptions' => ['style' => 'height: 100%; line-height: '.$lineHeight.'px;'],
        'hiddenFromExport' => true,
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'flags',
        'hidden' => true,
        'hiddenFromExport' => true,
        'format' => 'raw',
        'value' => function(){
            return null;
        }
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'id',
        'label' => 'Номер (ID)',
        'visible' => false,
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'created_at',
        'label' => 'Заведено',
        'hidden' => true,
        'content' => function($model){
            return (new \DateTime($model->created_at))->format('d-m-Y');
        }
    ],

    [ // For HTML
        'class' => '\app\widgets\columns\DataColumn',
        'attribute' => 'title',
        'format' => 'raw',
        'value' => function (\app\models\task\Task $task) {
            return \app\widgets\task\TitleLink::widget(['task' => $task]);
        },
        'hiddenFromExport' => true,
    ],
    [ // For Export
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'title',
        'format' => 'raw',
        'contentOptions' => ['style' => 'height: 100%;'],
        'visible' => false,
    ],
    [
        'class' => '\app\widgets\columns\DataColumn',
        'attribute' => 'body',
        'format' => 'raw',
        'value' => function (\app\models\task\Task $task) {
            return \app\widgets\task\ShortBody::widget(['task' => $task]);
        }
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'myTeamRoleId',
        'filterType' => \kartik\grid\GridView::FILTER_SELECT2,
        'filterInputOptions' => [
            'placeholder' => 'Выберите значение',
        ],
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'allowClear' => true,
            ],
        ],
        'filter' => \app\Rf\Modules\Users\models\User::current()->role->getMyTeamRoleFilter(),
        'format' => 'raw',
        'value' => function (\app\models\task\Task $task) {
            return \yii\bootstrap\Html::tag('span', $task->myTeamRole->label, ['class' => $task->myTeamRole->labelClass]);
        }
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'messagesList',
        'label' => 'Сообщений',
        //'filter' => \app\Rf\Modules\Users\models\User::current()->role->getMyTeamRoleFilter(),
        'format' => 'raw',
        'value' => function (\app\models\task\Task $task) {
            return Html::a(count($task->messagesList), '#', [
                'data-toggle' => 'popover',
                'data-trigger' => 'hover',
                'data-html' => 'true',
                'data-content' => (new \app\widgets\chat\Chat(['task' => $task]))->getSmall(),
            ]);
        },
        'hAlign' => \kartik\grid\GridView::ALIGN_CENTER,
        'vAlign' => \kartik\grid\GridView::ALIGN_CENTER,
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'messagesList',
        'label' => 'Вложений',
        //'filter' => \app\Rf\Modules\Users\models\User::current()->role->getMyTeamRoleFilter(),
        'format' => 'raw',
        'value' => function (\app\models\task\Task $task) {
            $messages = Message::find()->where(['task_id' => $task->id])->with('files')->all();

            $messagesPreview = [];

            foreach ($messages as $message) {
                $messagesPreview = \yii\helpers\ArrayHelper::merge($messagesPreview, \yii\helpers\ArrayHelper::getColumn($message->getFiles()->all(), 'path'));
            }

            return Html::a(count($messagesPreview) + count($task->attachments), ['task-full/attachments', 'id' => $task->id], [
                'role' => 'modal-remote'
            ]);
        },
        'hAlign' => \kartik\grid\GridView::ALIGN_CENTER,
        'vAlign' => \kartik\grid\GridView::ALIGN_CENTER,
    ],
    [ // For HTML
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'authorId',
        'filterType' => \kartik\grid\GridView::FILTER_SELECT2,
        'filterInputOptions' => [
            'placeholder' => 'Выберите значение',
        ],
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'allowClear' => true,
            ],
        ],
        'filter' => \app\Rf\Modules\Users\models\User::allList(),
        'format' => 'raw',
        'value' => function (\app\models\task\Task $task) {
            return \app\widgets\user\UserInfo::widget(['user' => $task->author]);
        },
        'hiddenFromExport' => true,
    ],
    [ // For Export
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'authorId',
        'filter' => \app\Rf\Modules\Users\models\User::allList(),
        'value' => 'author.name',
        'visible' => false,
    ],
    [ // For HTML
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'executorId',
        'filter' => \app\Rf\Modules\Users\models\User::allList(),
        'filterType' => \kartik\grid\GridView::FILTER_SELECT2,
        'filterInputOptions' => [
            'placeholder' => 'Выберите значение',
        ],
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'allowClear' => true,
            ],
        ],
        'format' => 'raw',
        'value' => function (\app\models\task\Task $task) {
            return \app\widgets\user\UserInfo::widget(['user' => $task->executor]);
        },
        'hiddenFromExport' => true,
    ],
    [ // For Export
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'executorId',
        'filter' => \app\Rf\Modules\Users\models\User::allList(),
        'format' => 'raw',
        'value' => 'executor.name',
        'visible' => false,
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'status_id',
        'filter' => \app\models\task\TaskStatus::list(),
        'filterType' => \kartik\grid\GridView::FILTER_SELECT2,
        'filterInputOptions' => [
            'placeholder' => 'Выберите значение',
        ],
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'allowClear' => true,
            ],
        ],
        'format' => 'raw',
        'value' => function (\app\models\task\Task $task) {
            return \app\widgets\task\TaskStatus::widget(['task' => $task]);
        },
    ],
//    [
//        'class' => '\kartik\grid\DataColumn',
//        'value' => function(\app\models\task\Task $task){
//            /** @var \app\models\team\TeamMember $member */
//            $member = \app\models\team\TeamMember::find()->where(['task_id' => $task->id, 'user_id' => \app\Rf\Modules\Users\models\User::current()->id])->one();
//            if($member->hasUnreadMessages){
//                return 'yes';
//            } else {
//                return 'no';
//            }
//        },
//    ],
    [
        'class' => '\kartik\grid\DataColumn',

        'attribute' => 'created_at',
        'filterType' => \kartik\grid\GridView::FILTER_DATE_RANGE,
        'filterWidgetOptions' => [
            'pluginOptions' => [
//                'timePicker' => true,
//                'timePickerIncrement' => 15,
                'timePicker24Hour' => true,
                'locale' => [
                    'format' => 'YYYY-MM-DD H:mm'
                ],
            ],
        ],
    ],

    [
        'class' => '\kartik\grid\DataColumn',
        'value' => 'executionTime',
        'label' => 'Время исполнения (ч)',
        'hAlign' => \kartik\grid\GridView::ALIGN_CENTER,
        'vAlign' => \kartik\grid\GridView::ALIGN_CENTER,
    ],

    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'finished_at',
        'filterType' => \kartik\grid\GridView::FILTER_DATE_RANGE,
        'filterWidgetOptions' => [
            'pluginOptions' => [
//                'timePicker' => true,
//                'timePickerIncrement' => 15,
                'timePicker24Hour' => true,
                'locale' => [
                    'format' => 'YYYY-MM-DD H:mm'
                ],
            ],
        ],
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign' => 'middle',
        'template' => \app\Rf\Modules\Users\models\User::current()->isAdmin ? '{full-view} {view} {update} {delete}' : '{full-view} {view}',
        'urlCreator' => function ($action, $model, $key, $index) {
            return Url::to([$action, 'id' => $key]);
        },
        'buttons' => [
            'full-view' => function ($url, $task) {
                return \yii\bootstrap\Html::a('<span class="fa fa-search"></span>',
                    Url::toRoute(['/task-full', 'taskId' => $task->id]),
                    ['data-pjax' => 0, 'title' => Yii::t('app', 'Full view'),]);
            },
        ],
        'viewOptions' => ['role' => 'modal-remote', 'title' => Yii::t('app', 'View'), 'data-toggle' => 'tooltip'],

        'updateOptions' =>
            ['role' => 'modal-remote', 'title' => Yii::t('app', 'Edit'), 'data-toggle' => 'tooltip'],
        'deleteOptions' => ['role' => 'modal-remote', 'title' => Yii::t('app', 'Delete'),
            'data-confirm' => false, 'data-method' => false,// for overide yii data api
            'data-request-method' => 'post',
            'data-toggle' => 'tooltip',
            'data-confirm-title' => 'Вы уверены?',
            'data-confirm-message' => 'Вы действительно хотите удалить данный запрос?'],
    ],

];   

views/task/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\task\Task */
/* @var $form yii\widgets\ActiveForm */

/* @var $author \app\models\team\TeamMember */
/* @var $executor \app\models\team\TeamMember */
?>

<div class="task-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'body')->textarea(['maxlength' => true]) ?>

    <?php
    //create only
    if (!is_null($executor)) {
        if(!$model->isNewRecord){
            echo $form->field($model, 'status_id')
                ->dropDownList(\app\models\task\TaskStatus::createOptionsList());
        }

        echo $form->field($executor, 'user_id')
            ->widget(\kartik\select2\Select2::class,[
                'data' => \app\Rf\Modules\Users\models\User::filterSelfAndAdminsList(),
            ])
            ->label(Yii::t('app', 'Executor'));

        echo $form->field($model, 'observersList')->widget(\kartik\select2\Select2::class, [
            'data' => \yii\helpers\ArrayHelper::map(\app\Rf\Modules\Users\models\User::find()->all(), 'id', 'name'),
            'pluginOptions' => [
                'multiple' => true,
            ],
        ]);
    } ?>

    <?php if (!Yii::$app->request->isAjax) { ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>

</div>

views/task/create.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\task\Task */
/* @var $author \app\models\team\TeamMember */
/* @var $executor \app\models\team\TeamMember */

?>
<div class="task-create">
    <?= $this->render('_form', [
        'model' => $model,
        'executor' => $executor,
    ]) ?>
</div>

views/task/update.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\task\Task */
?>
<div class="task-update">

    <?= $this->render('_form', [
        'model' => $model,
        'executor' => null,
    ]) ?>

</div>

views/task/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\task\Task */
?>
<div class="task-view">

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'body',
            //'status_id',
            [
                'label' => Yii::t('app', 'Status'),
                'format' => 'raw',
                'value' => \app\widgets\task\TaskStatus::widget(['task' => $model]),
            ],
            'created_at',
            'finished_at',
        ],
    ]) ?>

</div>